import { Request, Response } from "express";
import fs from "fs";
import Product from "../models/product.model"; // Adjust your path
import AppError from "../utils/appError.utils";
import catchAsync from "../utils/catchAsync.utils";
import sendResponse from "../utils/sendResponse.utils";
import { 
  uploadFileToCloudinary, 
  uploadMultipleFilesToCloudinary, 
  deleteFileFromCloudinary 
} from "../utils/cloudinary.utils";


/**
 * @desc    Get all products with category and brand details populated
 * @route   GET /api/v1/products
 */
export const getAll = catchAsync(async (req: Request, res: Response) => {
  // 1. Fetch products from MongoDB and automatically substitute relational IDs
  //    with their matching documents from the Category and Brand collections.
  const products = await Product.find()
    .populate("category", "name description") // Populates category field with only name and description
    .populate("brand", "name logo");          // Populates brand field with only name and logo

  // 2. Return clean response back to client
  sendResponse(res, {
    message: "Products fetched successfully",
    statusCode: 200,
    data: products,
  });
});













//* getbyid
/**
 * @desc    Get single product by ID with full category and brand details
 * @route   GET /api/v1/products/:id
 */
export const getById = catchAsync(async (req: Request, res: Response) => {
  const { id } = req.params;

  // Find product and swap out relational IDs with the actual referenced documents
  const product = await Product.findById(id)
    .populate("category", "name description")
    .populate("brand", "name logo");

  // If product does not exist, trigger the 404 handler immediately
  if (!product) {
    throw new AppError("Product not found", 404);
  }

  sendResponse(res, {
    message: "Product fetched successfully",
    statusCode: 200,
    data: product,
  });
});











/**
 * @desc    Create a new product with cover image and gallery array
 * @route   POST /api/v1/products
 */
export const create = catchAsync(async (req: Request, res: Response) => {
  const { 
    name, 
    description, 
    price, 
    stock, 
    category, 
    brand, 
    is_featured, 
    new_arrival 
  } = req.body;

  // 1. Cast req.files to match the shape generated by Express / Multer upload.fields()
  const files = req.files as { [fieldname: string]: Express.Multer.File[] } | undefined;

  const coverImageFile = files?.["cover_image"]?.[0]; // Get the single file object
  const galleryFiles = files?.["images"];             // Get the array of file objects

  // 2. Structural checks before hitting cloud APIs
  if (!coverImageFile) {
    // If cover is missing, drop any attached gallery files from server memory instantly
    if (galleryFiles) galleryFiles.forEach(f => { if (fs.existsSync(f.path)) fs.unlinkSync(f.path); });
    throw new AppError("Product cover image is required", 400);
  }

  if (!galleryFiles || galleryFiles.length === 0) {
    if (fs.existsSync(coverImageFile.path)) fs.unlinkSync(coverImageFile.path);
    throw new AppError("At least one gallery image is required in 'images' field", 400);
  }

  // Tracking containers for automated crash rollbacks
  let uploadedCover: { path: string; public_id: string } | null = null;
  let uploadedGallery: { path: string; public_id: string }[] = [];

  try {
    // 3. Fire single image helper for the cover graphics layout
    const coverResult = await uploadFileToCloudinary(coverImageFile, "/products/covers");
    uploadedCover = coverResult;

    // 4. Fire array loop helper for the multi-picture gallery folder
    const galleryResult = await uploadMultipleFilesToCloudinary(galleryFiles, "/products/gallery");
    uploadedGallery = galleryResult;

    // 5. Instantly map parameters onto your Mongoose Schema structure
    const product = new Product({
      name,
      description,
      price,
      stock,
      category,
      brand,
      is_featured: is_featured === "false" ? false : true, // Handle form-data string transformations safely
      new_arrival: new_arrival === "false" ? false : true,
      cover_image: uploadedCover, // Single structure: { path, public_id }
      images: uploadedGallery     // Array structure: [{ path, public_id }, ...]
    });

    // 6. Save data model into MongoDB 
    await product.save();

    sendResponse(res, {
      message: `Product '${product.name}' created successfully`,
      statusCode: 201,
      data: product
    });

  } catch (error) {
    // 7. CRITICAL CLEANUP: If DB save crashes, immediately drop everything out of your Cloudinary bucket
    if (uploadedCover?.public_id) {
      await deleteFileFromCloudinary(uploadedCover.public_id);
    }
    
    if (uploadedGallery.length > 0) {
      for (const img of uploadedGallery) {
        await deleteFileFromCloudinary(img.public_id);
      }
    }

    // Secondary fallback cleanup for any remaining stray disk fragments
    if (coverImageFile && fs.existsSync(coverImageFile.path)) fs.unlinkSync(coverImageFile.path);
    if (galleryFiles) galleryFiles.forEach(f => { if (fs.existsSync(f.path)) fs.unlinkSync(f.path); });

    throw error;
  }
});



/**
 * @desc    Update product text data and handle cover/gallery file swaps
 * @route   PUT /api/v1/products/:id
 */
export const update = catchAsync(async (req: Request, res: Response) => {
  const { id } = req.params;
  const { name, description, price, stock, category, brand, is_featured, new_arrival } = req.body;

  // 1. Cast incoming files from upload.fields()
  const files = req.files as { [fieldname: string]: Express.Multer.File[] } | undefined;
  const newCoverFile = files?.["cover_image"]?.[0]; // Get potential new single cover file
  const newGalleryFiles = files?.["images"];          // Get potential new gallery files array

  // 2. Fetch existing product to verify existence and grab old image IDs
  const existingProduct = await Product.findById(id);
  if (!existingProduct) {
    // Safety cleanup of any newly uploaded local temp files if product doesn't exist
    if (newCoverFile && fs.existsSync(newCoverFile.path)) fs.unlinkSync(newCoverFile.path);
    if (newGalleryFiles) newGalleryFiles.forEach(f => { if (fs.existsSync(f.path)) fs.unlinkSync(f.path); });
    throw new AppError("Product not found", 404);
  }

  // 3. Build basic update payload object with incoming text inputs
  const updateData: any = {
    name,
    description,
    price,
    stock,
    category,
    brand,
  };

  // Safe type transformations for form-data strings
  if (is_featured !== undefined) updateData.is_featured = is_featured === "false" ? false : true;
  if (new_arrival !== undefined) updateData.new_arrival = new_arrival === "false" ? false : true;

  // Track old asset tracking keys for success cleanup execution phases
  const oldCoverPublicId = existingProduct.cover_image?.public_id;
  const oldGalleryImages = existingProduct.images || [];

  // Track newly uploaded cloud assets for crash-rollback fail-safes
  let newUploadedCover: { path: string; public_id: string } | null = null;
  let newUploadedGallery: { path: string; public_id: string }[] = [];

  try {
    // 4. Handle Single Cover Image Swap
    if (newCoverFile) {
      const coverResult = await uploadFileToCloudinary(newCoverFile, "/products/covers");
      updateData.cover_image = coverResult;
      newUploadedCover = coverResult; // Bookmark for crash protection
    }

    // 5. Handle Gallery Array Swap
    if (newGalleryFiles && newGalleryFiles.length > 0) {
      const galleryResult = await uploadMultipleFilesToCloudinary(newGalleryFiles, "/products/gallery");
      updateData.images = galleryResult;
      newUploadedGallery = galleryResult; // Bookmark for crash protection
    }

    // 6. Commit all accumulated updates directly to MongoDB
    const updatedProduct = await Product.findByIdAndUpdate(id, updateData, {
      new: true,
      runValidators: true,
    });

    // 7. SUCCESS CLEANUP: Purge old files off your Cloudinary drive permanently
    // Only run this if a new cover file was uploaded successfully
    if (newCoverFile && oldCoverPublicId) {
      await deleteFileFromCloudinary(oldCoverPublicId);
    }

    // Only run this if a new gallery array was uploaded successfully
    if (newGalleryFiles && newGalleryFiles.length > 0 && oldGalleryImages.length > 0) {
      for (const img of oldGalleryImages) {
        await deleteFileFromCloudinary(img.public_id);
      }
    }

    sendResponse(res, {
      message: "Product updated successfully",
      statusCode: 200,
      data: updatedProduct,
    });

  } catch (error) {
    // 8. FAIL-SAFE CRASH CLEANUP: If DB updates crash, instantly erase the NEW images from Cloudinary
    if (newUploadedCover?.public_id) {
      await deleteFileFromCloudinary(newUploadedCover.public_id);
    }
    if (newUploadedGallery.length > 0) {
      for (const img of newUploadedGallery) {
        await deleteFileFromCloudinary(img.public_id);
      }
    }

    // Secondary local server storage flush fallback
    if (newCoverFile && fs.existsSync(newCoverFile.path)) fs.unlinkSync(newCoverFile.path);
    if (newGalleryFiles) newGalleryFiles.forEach(f => { if (fs.existsSync(f.path)) fs.unlinkSync(f.path); });

    throw error;
  }
});



/**
 * @desc    Delete a product and purge its entire media gallery from Cloudinary
 * @route   DELETE /api/v1/products/:id
 */
export const remove = catchAsync(async (req: Request, res: Response) => {
  const { id } = req.params;

  // 1. Fetch product data first to grab the image structural blueprints
  const product = await Product.findById(id);
  if (!product) {
    throw new AppError("Product not found", 404);
  }

  // 2. Clear out the single primary cover image from Cloudinary
  if (product.cover_image?.public_id) {
    await deleteFileFromCloudinary(product.cover_image.public_id);
  }

  // 3. Loop through and clear out the entire gallery images array from Cloudinary
  if (product.images && product.images.length > 0) {
    for (const image of product.images) {
      if (image.public_id) {
        await deleteFileFromCloudinary(image.public_id);
      }
    }
  }

  // 4. Wipe the record completely out of your MongoDB collection
  await product.deleteOne();

  sendResponse(res, {
    message: `Product '${product.name}' and all its media files deleted successfully`,
    statusCode: 200,
    data: null,
  });
});
